function [] = compressionlevel_relay(varargin);


handles2 = guidata(gcf);
poscomp = get(handles2.popCompression_main, 'value');

if handles2.resolutionVideo(1) == 1280;
    if poscomp == 1;
        handles2.CurrenCompression = 15;
    elseif poscomp == 2;
        handles2.CurrenCompression = 14;
    elseif poscomp == 3;
        handles2.CurrenCompression = 13;
    elseif poscomp == 4;
        handles2.CurrenCompression = 12;
    elseif poscomp == 5;
        handles2.CurrenCompression = 11;
    elseif poscomp == 6;
        handles2.CurrenCompression = 10;
    elseif poscomp == 7;
        handles2.CurrenCompression = 9;
    elseif poscomp == 8;
        handles2.CurrenCompression = 8;
    elseif poscomp == 9;
        handles2.CurrenCompression = 7;
    elseif poscomp == 10;
        handles2.CurrenCompression = 6;
    elseif poscomp == 11;
        handles2.CurrenCompression = 5;
    elseif poscomp == 12;
        handles2.CurrenCompression = 4;
    elseif poscomp == 13;
        handles2.CurrenCompression = 3;
    end;
    
elseif handles2.resolutionVideo(1) == 1920;
    if poscomp == 1;
        handles2.CurrenCompression = 35;
    elseif poscomp == 2;
        handles2.CurrenCompression = 34;
    elseif poscomp == 3;
        handles2.CurrenCompression = 33;
    elseif poscomp == 4;
        handles2.CurrenCompression = 32;
    elseif poscomp == 5;
        handles2.CurrenCompression = 31;
    elseif poscomp == 6;
        handles2.CurrenCompression = 30;
    elseif poscomp == 7;
        handles2.CurrenCompression = 29;
    elseif poscomp == 8;
        handles2.CurrenCompression = 28;
    elseif poscomp == 9;
        handles2.CurrenCompression = 27;
    elseif poscomp == 10;
        handles2.CurrenCompression = 26;
    elseif poscomp == 11;
        handles2.CurrenCompression = 25;
    elseif poscomp == 12;
        handles2.CurrenCompression = 24;
    elseif poscomp == 13;
        handles2.CurrenCompression = 23;
    elseif poscomp == 14;
        handles2.CurrenCompression = 22;
    elseif poscomp == 15;
        handles2.CurrenCompression = 21;
    elseif poscomp == 16;
        handles2.CurrenCompression = 20;
    elseif poscomp == 17;
        handles2.CurrenCompression = 19;
    elseif poscomp == 18;
        handles2.CurrenCompression = 18;
    elseif poscomp == 19;
        handles2.CurrenCompression = 17;
    elseif poscomp == 20;
        handles2.CurrenCompression = 16;
    elseif poscomp == 21;
        handles2.CurrenCompression = 15;
    elseif poscomp == 22;
        handles2.CurrenCompression = 14;
    elseif poscomp == 23;
        handles2.CurrenCompression = 13;
    elseif poscomp == 24;
        handles2.CurrenCompression = 12;
    elseif poscomp == 25;
        handles2.CurrenCompression = 11;
    elseif poscomp == 26;
        handles2.CurrenCompression = 10;
    elseif poscomp == 27;
        handles2.CurrenCompression = 9;
    elseif poscomp == 28;
        handles2.CurrenCompression = 8;
    elseif poscomp == 29;
        handles2.CurrenCompression = 7;
    elseif poscomp == 30;
        handles2.CurrenCompression = 6;
    elseif poscomp == 31;
        handles2.CurrenCompression = 5;
    elseif poscomp == 32;
        handles2.CurrenCompression = 4;
    elseif poscomp == 33;
        handles2.CurrenCompression = 3;
    elseif poscomp == 34;
        handles2.CurrenCompression = 2;
    end;

elseif handles2.resolutionVideo(1) == 3840;
    
    if poscomp == 1;
        handles2.CurrenCompression = 150;
    elseif poscomp == 2;
        handles2.CurrenCompression = 145;
    elseif poscomp == 3;
        handles2.CurrenCompression = 140;
    elseif poscomp == 4;
        handles2.CurrenCompression = 135;
    elseif poscomp == 5;
        handles2.CurrenCompression = 130;
    elseif poscomp == 6;
        handles2.CurrenCompression = 125;
    elseif poscomp == 7;
        handles2.CurrenCompression = 120;
    elseif poscomp == 8;
        handles2.CurrenCompression = 115;
    elseif poscomp == 9;
        handles2.CurrenCompression = 110;
    elseif poscomp == 10;
        handles2.CurrenCompression = 105;
    elseif poscomp == 11;
        handles2.CurrenCompression = 100;
    elseif poscomp == 12;
        handles2.CurrenCompression = 95;
    elseif poscomp == 13;
        handles2.CurrenCompression = 90;
    elseif poscomp == 14;
        handles2.CurrenCompression = 85;
    elseif poscomp == 15;
        handles2.CurrenCompression = 80;
    elseif poscomp == 16;
        handles2.CurrenCompression = 75;
    elseif poscomp == 17;
        handles2.CurrenCompression = 70;
    elseif poscomp == 18;
        handles2.CurrenCompression = 65;
    elseif poscomp == 19;
        handles2.CurrenCompression = 60;
    elseif poscomp == 20;
        handles2.CurrenCompression = 55;
    elseif poscomp == 21;
        handles2.CurrenCompression = 50;
    elseif poscomp == 22;
        handles2.CurrenCompression = 45;
    elseif poscomp == 23;
        handles2.CurrenCompression = 40;
    elseif poscomp == 24;
        handles2.CurrenCompression = 35;
    elseif poscomp == 25;
        handles2.CurrenCompression = 30;
    elseif poscomp == 26;
        handles2.CurrenCompression = 25;
    elseif poscomp == 27;
        handles2.CurrenCompression = 20;
    elseif poscomp == 28;
        handles2.CurrenCompression = 15;
    elseif poscomp == 29;
        handles2.CurrenCompression = 10;
    elseif poscomp == 30;
        handles2.CurrenCompression = 5;
    end;
    
end;
guidata(handles2.hf_w2_welcome, handles2);


% jCBModel.uncheckIndex(1);
% jCBModel.uncheckIndex(3);