function [] = compressionlevel4K_main(varargin);


handles = guidata(gcf);
poscomp = get(handles.popCompression4K_main, 'value');

if poscomp == 1;
    handles2.CurrenCompression = 150;
elseif poscomp == 2;
    handles2.CurrenCompression = 145;
elseif poscomp == 3;
    handles2.CurrenCompression = 140;
elseif poscomp == 4;
    handles2.CurrenCompression = 135;
elseif poscomp == 5;
    handles2.CurrenCompression = 130;
elseif poscomp == 6;
    handles2.CurrenCompression = 125;
elseif poscomp == 7;
    handles2.CurrenCompression = 120;
elseif poscomp == 8;
    handles2.CurrenCompression = 115;
elseif poscomp == 9;
    handles2.CurrenCompression = 110;
elseif poscomp == 10;
    handles2.CurrenCompression = 105;
elseif poscomp == 11;
    handles2.CurrenCompression = 100;
elseif poscomp == 12;
    handles2.CurrenCompression = 95;
elseif poscomp == 13;
    handles2.CurrenCompression = 90;
elseif poscomp == 14;
    handles2.CurrenCompression = 85;
elseif poscomp == 15;
    handles2.CurrenCompression = 80;
elseif poscomp == 16;
    handles2.CurrenCompression = 75;
elseif poscomp == 17;
    handles2.CurrenCompression = 70;
elseif poscomp == 18;
    handles2.CurrenCompression = 65;
elseif poscomp == 19;
    handles2.CurrenCompression = 60;
elseif poscomp == 20;
    handles2.CurrenCompression = 55;
elseif poscomp == 21;
    handles2.CurrenCompression = 50;
elseif poscomp == 22;
    handles2.CurrenCompression = 45;
elseif poscomp == 23;
    handles2.CurrenCompression = 40;
elseif poscomp == 24;
    handles2.CurrenCompression = 35;
elseif poscomp == 25;
    handles2.CurrenCompression = 30;
elseif poscomp == 26;
    handles2.CurrenCompression = 25;
elseif poscomp == 27;
    handles2.CurrenCompression = 20;
elseif poscomp == 28;
    handles2.CurrenCompression = 15;
elseif poscomp == 29;
    handles2.CurrenCompression = 10;
elseif poscomp == 30;
    handles2.CurrenCompression = 5;
end;
 
guidata(handles.hf_w1_welcome, handles);

