function [] = popCompression_screen(varargin);


handles = guidata(gcf);
poscomp = get(handles.popCompression_screen, 'value');


resolutionVideo = handles.resolutionVideoScreen;
if resolutionVideo(1) == 1280;
    if poscomp == 1;
        CurrenCompression = 15;
    elseif poscomp == 2;
        CurrenCompression = 14;
    elseif poscomp == 3;
        CurrenCompression = 13;
    elseif poscomp == 4;
        CurrenCompression = 12;
    elseif poscomp == 5;
        CurrenCompression = 11;
    elseif poscomp == 6;
        CurrenCompression = 10;
    elseif poscomp == 7;
        CurrenCompression = 9;
    elseif poscomp == 8;
        CurrenCompression = 8;
    elseif poscomp == 9;
        CurrenCompression = 7;
    elseif poscomp == 10;
        CurrenCompression = 6;
    elseif poscomp == 11;
        CurrenCompression = 5;
    elseif poscomp == 12;
        CurrenCompression = 4;
    elseif poscomp == 13;
        CurrenCompression = 3;
    elseif poscomp == 14;
        CurrenCompression = 0;
    end;
    
elseif resolutionVideo(1) == 1920;
    if poscomp == 1;
        CurrenCompression = 35;
    elseif poscomp == 2;
        CurrenCompression = 34;
    elseif poscomp == 3;
        CurrenCompression = 33;
    elseif poscomp == 4;
        CurrenCompression = 32;
    elseif poscomp == 5;
        CurrenCompression = 31;
    elseif poscomp == 6;
        CurrenCompression = 30;
    elseif poscomp == 7;
        CurrenCompression = 29;
    elseif poscomp == 8;
        CurrenCompression = 28;
    elseif poscomp == 9;
        CurrenCompression = 27;
    elseif poscomp == 10;
        CurrenCompression = 26;
    elseif poscomp == 11;
        CurrenCompression = 25;
    elseif poscomp == 12;
        CurrenCompression = 24;
    elseif poscomp == 13;
        CurrenCompression = 23;
    elseif poscomp == 14;
        CurrenCompression = 22;
    elseif poscomp == 15;
        CurrenCompression = 21;
    elseif poscomp == 16;
        CurrenCompression = 20;
    elseif poscomp == 17;
        CurrenCompression = 19;
    elseif poscomp == 18;
        CurrenCompression = 18;
    elseif poscomp == 19;
        CurrenCompression = 17;
    elseif poscomp == 20;
        CurrenCompression = 16;
    elseif poscomp == 21;
        CurrenCompression = 15;
    elseif poscomp == 22;
        CurrenCompression = 14;
    elseif poscomp == 23;
        CurrenCompression = 13;
    elseif poscomp == 24;
        CurrenCompression = 12;
    elseif poscomp == 25;
        CurrenCompression = 11;
    elseif poscomp == 26;
        CurrenCompression = 10;
    elseif poscomp == 27;
        CurrenCompression = 9;
    elseif poscomp == 28;
        CurrenCompression = 8;
    elseif poscomp == 29;
        CurrenCompression = 7;
    elseif poscomp == 30;
        CurrenCompression = 6;
    elseif poscomp == 31;
        CurrenCompression = 5;
    elseif poscomp == 32;
        CurrenCompression = 4;
    elseif poscomp == 33;
        CurrenCompression = 3;
    elseif poscomp == 34;
        CurrenCompression = 2;
    elseif poscomp == 35;
        CurrenCompression = 0;
    end;

elseif resolutionVideo(1) == 3840;
    if poscomp == 1;
        CurrenCompression = 250;
    elseif poscomp == 2;
        CurrenCompression = 240;
    elseif poscomp == 3;
        CurrenCompression = 230;
    elseif poscomp == 4;
        CurrenCompression = 220;
    elseif poscomp == 5;
        CurrenCompression = 210;
    elseif poscomp == 6;
        CurrenCompression = 200;
    elseif poscomp == 7;
        CurrenCompression = 190;
    elseif poscomp == 8;
        CurrenCompression = 180;
    elseif poscomp == 9;
        CurrenCompression = 170;
    elseif poscomp == 10;
        CurrenCompression = 160;
    elseif poscomp == 11;
        CurrenCompression = 150;
    elseif poscomp == 12;
        CurrenCompression = 140;
    elseif poscomp == 13;
        CurrenCompression = 130;
    elseif poscomp == 14;
        CurrenCompression = 120;
    elseif poscomp == 15;
        CurrenCompression = 110;
    elseif poscomp == 16;
        CurrenCompression = 100;
    elseif poscomp == 17;
        CurrenCompression = 90;
    elseif poscomp == 18;
        CurrenCompression = 80;
    elseif poscomp == 19;
        CurrenCompression = 70;
    elseif poscomp == 20;
        CurrenCompression = 60;
    elseif poscomp == 21;
        CurrenCompression = 50;
    elseif poscomp == 22;
        CurrenCompression = 40;
    elseif poscomp == 23;
        CurrenCompression = 30;
    elseif poscomp == 24;
        CurrenCompression = 20;
    elseif poscomp == 25;
        CurrenCompression = 10;
    elseif poscomp == 26;
        CurrenCompression = 0;
    end;
    
end;

handles.CurrenCompressionScreen = CurrenCompression;
handles.listDropCompressionPosScreen = poscomp;
guidata(handles.hf_w1_welcome, handles);


% jCBModel.uncheckIndex(1);
% jCBModel.uncheckIndex(3);