function [] = popCompression_single(varargin);


handles = guidata(gcf);
poscomp = get(handles.popCompression_single, 'value');


if handles.activeVideo_single == 1;
    resolutionVideo = handles.resolutionVideoPanning;
elseif handles.activeVideo_single == 2;
    resolutionVideo = handles.resolutionVideo4K;
end;


if resolutionVideo(1) == 1280;
    if poscomp == 1;
        CurrenCompression = 15;
    elseif poscomp == 2;
        CurrenCompression = 14;
    elseif poscomp == 3;
        CurrenCompression = 13;
    elseif poscomp == 4;
        CurrenCompression = 12;
    elseif poscomp == 5;
        CurrenCompression = 11;
    elseif poscomp == 6;
        CurrenCompression = 10;
    elseif poscomp == 7;
        CurrenCompression = 9;
    elseif poscomp == 8;
        CurrenCompression = 8;
    elseif poscomp == 9;
        CurrenCompression = 7;
    elseif poscomp == 10;
        CurrenCompression = 6;
    elseif poscomp == 11;
        CurrenCompression = 5;
    elseif poscomp == 12;
        CurrenCompression = 4;
    elseif poscomp == 13;
        CurrenCompression = 3;
    end;
    
elseif resolutionVideo(1) == 1920;
    if poscomp == 1;
        CurrenCompression = 35;
    elseif poscomp == 2;
        CurrenCompression = 34;
    elseif poscomp == 3;
        CurrenCompression = 33;
    elseif poscomp == 4;
        CurrenCompression = 32;
    elseif poscomp == 5;
        CurrenCompression = 31;
    elseif poscomp == 6;
        CurrenCompression = 30;
    elseif poscomp == 7;
        CurrenCompression = 29;
    elseif poscomp == 8;
        CurrenCompression = 28;
    elseif poscomp == 9;
        CurrenCompression = 27;
    elseif poscomp == 10;
        CurrenCompression = 26;
    elseif poscomp == 11;
        CurrenCompression = 25;
    elseif poscomp == 12;
        CurrenCompression = 24;
    elseif poscomp == 13;
        CurrenCompression = 23;
    elseif poscomp == 14;
        CurrenCompression = 22;
    elseif poscomp == 15;
        CurrenCompression = 21;
    elseif poscomp == 16;
        CurrenCompression = 20;
    elseif poscomp == 17;
        CurrenCompression = 19;
    elseif poscomp == 18;
        CurrenCompression = 18;
    elseif poscomp == 19;
        CurrenCompression = 17;
    elseif poscomp == 20;
        CurrenCompression = 16;
    elseif poscomp == 21;
        CurrenCompression = 15;
    elseif poscomp == 22;
        CurrenCompression = 14;
    elseif poscomp == 23;
        CurrenCompression = 13;
    elseif poscomp == 24;
        CurrenCompression = 12;
    elseif poscomp == 25;
        CurrenCompression = 11;
    elseif poscomp == 26;
        CurrenCompression = 10;
    elseif poscomp == 27;
        CurrenCompression = 9;
    elseif poscomp == 28;
        CurrenCompression = 8;
    elseif poscomp == 29;
        CurrenCompression = 7;
    elseif poscomp == 30;
        CurrenCompression = 6;
    elseif poscomp == 31;
        CurrenCompression = 5;
    elseif poscomp == 32;
        CurrenCompression = 4;
    elseif poscomp == 33;
        CurrenCompression = 3;
    elseif poscomp == 34;
        CurrenCompression = 2;
    end;

elseif resolutionVideo(1) == 3840;
    
    if poscomp == 1;
        CurrenCompression = 150;
    elseif poscomp == 2;
        CurrenCompression = 145;
    elseif poscomp == 3;
        CurrenCompression = 140;
    elseif poscomp == 4;
        CurrenCompression = 135;
    elseif poscomp == 5;
        CurrenCompression = 130;
    elseif poscomp == 6;
        CurrenCompression = 125;
    elseif poscomp == 7;
        CurrenCompression = 120;
    elseif poscomp == 8;
        CurrenCompression = 115;
    elseif poscomp == 9;
        CurrenCompression = 110;
    elseif poscomp == 10;
        CurrenCompression = 105;
    elseif poscomp == 11;
        CurrenCompression = 100;
    elseif poscomp == 12;
        CurrenCompression = 95;
    elseif poscomp == 13;
        CurrenCompression = 90;
    elseif poscomp == 14;
        CurrenCompression = 85;
    elseif poscomp == 15;
        CurrenCompression = 80;
    elseif poscomp == 16;
        CurrenCompression = 75;
    elseif poscomp == 17;
        CurrenCompression = 70;
    elseif poscomp == 18;
        CurrenCompression = 65;
    elseif poscomp == 19;
        CurrenCompression = 60;
    elseif poscomp == 20;
        CurrenCompression = 55;
    elseif poscomp == 21;
        CurrenCompression = 50;
    elseif poscomp == 22;
        CurrenCompression = 45;
    elseif poscomp == 23;
        CurrenCompression = 40;
    elseif poscomp == 24;
        CurrenCompression = 35;
    elseif poscomp == 25;
        CurrenCompression = 30;
    elseif poscomp == 26;
        CurrenCompression = 25;
    elseif poscomp == 27;
        CurrenCompression = 20;
    elseif poscomp == 28;
        CurrenCompression = 15;
    elseif poscomp == 29;
        CurrenCompression = 10;
    elseif poscomp == 30;
        CurrenCompression = 5;
    end;
    
end;

if handles.activeVideo_single == 1;
    handles.CurrenCompressionPanning = CurrenCompression;
    handles.listDropCompressionPosPanning = poscomp;
elseif handles.activeVideo_single == 2;
    handles.CurrenCompression4K = CurrenCompression;
    handles.listDropCompressionPos4K = poscomp;
end;
guidata(handles.hf_w1_welcome, handles);


% jCBModel.uncheckIndex(1);
% jCBModel.uncheckIndex(3);